<a href="https://colab.research.google.com/github/pranavtithombre/HEART-DISEASE-PREDICTION-USING-ML/blob/main/HEART_DISEASE_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
df = pd.read_csv("/content/Heart Disease UCI dataset.zip")

In [ ]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No

In [ ]:
df.shape

(1025, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      1025 non-null   int64
 1   sex                      1025 non-null   object
 2   chest_pain_type          1025 non-null   object
 3   resting_blood_pressure   1025 non-null   int64
 4   cholestoral              1025 non-null   int64
 5   fasting_blood_sugar      1025 non-null   object
 6   rest_ecg                 1025 non-null   object
 7   Max_heart_rate           1025 non-null   int64
 8   exercise_induced_angina  1025 non-null   object
dtypes: int64(4), object(5)
memory usage: 72.2+ KB

In [ ]:
df.describe()

               age  resting_blood_pressure  cholestoral  Max_heart_rate
count  1025.000000             1025.000000   1025.00000     1025.000000
mean     54.434146              131.611707    246.00000      149.114146
std       9.072290               17.516718     51.59251       23.005724
min      29.000000               94.000000    126.00000       71.000000
25%      48.000000              120.000000    211.00000      132.000000
50%      56.000000              130.000000    240.00000      152.000000
75%      61.000000              140.000000    275.00000      166.000000
max      77.000000              200.000000    564.00000      202.000000

In [ ]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholestoral                0
fasting_blood_sugar        0
rest_ecg                   0
Max_heart_rate             0
exercise_induced_angina    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(723)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

NameError: name 'X' is not defined

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)

In [ ]:
age = int(input("Enter Age: "))
sex = int(input("Sex (1=Male, 0=Female): "))
cp = int(input("Chest Pain Type: "))
trestbps = int(input("BP: "))
chol = int(input("Cholesterol: "))
fbs = int(input("Fasting Sugar: "))
restecg = int(input("ECG: "))
thalach = int(input("Max Heart Rate: "))
exang = int(input("Exercise Angina: "))


input_data = np.array([[age, sex, cp, trestbps, chol, fbs, restecg,
                        thalach, exang]])

scaler = StandardScaler()
input_data_scaled = scaler.fit_transform(input_data)

prediction = model.predict(input_data_scaled)

if prediction[0] == 0:
    print("No Heart Disease ")
else:
    print("Heart Disease Detected ")

In [ ]:
prediction = model.predict(input_data_scaled)
print(prediction)